#string concatenation double,single,tripple quote
print('hello')
print("hello")
print('''hello''')
print('"hello"')
print(''''hello''')  
print("'hello'")
print("'''hello'''")
print(''' 'hello' ''')
print(''' "hello" ''')